POST  http://localhost:9000/users/create
Content-Type: application/json

{
    "userName": "David Lozada",
    "password": "000000",
    "email": "greuddydlp16@gmail.com"
}

###
POST  http://localhost:9000/auth/login
Content-Type: application/json

{
    "userName": "David Lozada",
    "password": "000000"
}

###
GET http://localhost:9000/users/user