POST  http://localhost:9000/users/create
Content-Type: application/json

{
    "firstName": "David",
    "lastName": "Lozada",
    "userName": "David Lozada",
    "password": "000000",
    "email": "greuddydlp16@gmail.com",
    "idRole": 1
}

###
POST  http://localhost:9000/auth/login
Content-Type: application/json

{
    "userName": "David Lozada",
    "password": "000000"
}

###
GET http://localhost:9000/users/user
Authorization: Bearer pN3l3V2dNBnHCVXHiaSTR312Q4A9aq